#!/bin/bash

sudo apt-get install git-core

localdir="$HOME/web_server"

if [ -d "$localdir" ]; then
    rm -rf "$localdir"
fi

cd $HOME
git clone git@github.com:FireworksProject/web_server.git

web_server/bin/bootstrap_ubuntu

echo "OK - toehold is done"
