#!/bin/bash

sudo apt-get install -y git-core

localdir="$HOME/web_server"

if [ -d "$localdir" ]; then
    rm -rf "$localdir"
fi

cd $HOME
git clone git://github.com/FireworksProject/web_server.git || \
    echo "failed to download web_server repository: try again"

sudo web_server/bin/bootstrap_ubuntu || \
    echo "failed to install ubuntu packages: try again"

echo "OK - toehold is done"
